name: Deploy React to Hostinger
on:
  repository_dispatch: # C'est le signal de WordPress !
    types: [cms_update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          WPGRAPHQL_URL: ${{ secrets.WPGRAPHQL_URL }}
          SITE_URL: ${{ secrets.SITE_URL }}
          NODE_ENV: production
          GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
          GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
          GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
          GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
          GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}
          GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
          GATSBY_FIREBASE_MEASUREMENT_ID: ${{ secrets.GATSBY_FIREBASE_MEASUREMENT_ID }}
          GATSBY_BREVO_API_KEY: ${{ secrets.GATSBY_BREVO_API_KEY }}
          GATSBY_BREVO_URL: ${{ secrets.GATSBY_BREVO_URL }}
          GATSBY_FIREBASE_COLLECTION_SUBMISSIONS: ${{ secrets.GATSBY_FIREBASE_COLLECTION_SUBMISSIONS }}
      - name: Deploy via SSH (Hostinger)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_IP }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASS }}
          source: "dist/*" # Le dossier build de React
          target: "/home/customer/www/thatmuch.fr/public_html"
